@startuml
class com.transportation.metrobas.MetrobasApplication
class com.transportation.metrobas.auth.AuthController
class com.transportation.metrobas.auth.AuthService
class com.transportation.metrobas.auth.ChangePasswordDto
class com.transportation.metrobas.auth.CustomAccessDeniedHandler
class com.transportation.metrobas.auth.CustomLogoutHandler
class com.transportation.metrobas.auth.JwtAuthFilter
class com.transportation.metrobas.auth.JwtService
class com.transportation.metrobas.auth.LoginRequest
class com.transportation.metrobas.auth.LoginResponse
class com.transportation.metrobas.auth.RegisterRequest
class com.transportation.metrobas.auth.SecurityConfiguration
class com.transportation.metrobas.chat.ChatController
class com.transportation.metrobas.chat.ChatService
class com.transportation.metrobas.chat.Message
class com.transportation.metrobas.exception.EmailAlreadyExist
class com.transportation.metrobas.exception.ExceptionHandlerAdvice
class com.transportation.metrobas.exception.PasswordNotMatch
class com.transportation.metrobas.gtfs.Agency
class com.transportation.metrobas.gtfs.Route
class com.transportation.metrobas.gtfs.RouteController
class com.transportation.metrobas.gtfs.RouteDto
class com.transportation.metrobas.gtfs.RouteService
class com.transportation.metrobas.gtfs.Stop
class com.transportation.metrobas.gtfs.StopTimes
class com.transportation.metrobas.gtfs.Transfer
class com.transportation.metrobas.gtfs.TransferStops
class com.transportation.metrobas.gtfs.Trip
class com.transportation.metrobas.gtfs.TripPoints
class com.transportation.metrobas.journey.JourneyController
class com.transportation.metrobas.journey.JourneyRequest
class com.transportation.metrobas.journey.JourneyResponse
class com.transportation.metrobas.journey.JourneyService
class com.transportation.metrobas.journey.Location
class com.transportation.metrobas.journey.MCRaptor
class com.transportation.metrobas.journey.StopLabel
class com.transportation.metrobas.journey.SubTrip
class com.transportation.metrobas.report.Report
class com.transportation.metrobas.report.ReportController
class com.transportation.metrobas.report.ReportRequest
class com.transportation.metrobas.report.ReportService
class com.transportation.metrobas.savedplaces.SaveSavedPlaceDto
class com.transportation.metrobas.savedplaces.SavedPlace
class com.transportation.metrobas.savedplaces.SavedPlaceController
class com.transportation.metrobas.savedplaces.SavedPlaceService
class com.transportation.metrobas.swagger.OpenApiConfiguration
class com.transportation.metrobas.user.User
class com.transportation.metrobas.user.UserAdabter
class com.transportation.metrobas.user.UserController
class com.transportation.metrobas.user.UserDto
class com.transportation.metrobas.user.UserService
class com.transportation.metrobas.util.DistanceFromStop
class edu.tcu.cs.hogwartsartifactsonline.security.CorsConfiguration
class io.jsonwebtoken.Claims
class io.jsonwebtoken.Jwts
class io.jsonwebtoken.io.Decoders
class io.jsonwebtoken.security.Keys
class io.swagger.v3.oas.annotations.enums.SecuritySchemeIn
class io.swagger.v3.oas.annotations.enums.SecuritySchemeType
class jakarta.persistence.Column
class jakarta.persistence.criteria.CriteriaBuilder
class jakarta.servlet.FilterChain
class jakarta.servlet.ServletException
class jakarta.servlet.http.HttpServletRequest
class jakarta.servlet.http.HttpServletResponse
class jakarta.validation.constraints.Email
class jakarta.validation.constraints.Max
class jakarta.validation.constraints.Min
class java.io.IOException
class java.lang.RuntimeException
class java.math.BigDecimal
class java.security.Principal
class java.time.Duration
class java.time.LocalDateTime
class java.time.LocalTime
class java.util.ArrayList
class java.util.Collection
class java.util.Date
class java.util.List
class java.util.Objects
class java.util.Optional
class java.util.function.Function
class java.util.stream.Collectors
class javax.crypto.SecretKey
class jdk.dynalink.linker.LinkerServices
class org.springframework.boot.SpringApplication
class org.springframework.http.HttpStatus
class org.springframework.http.ResponseEntity
class org.springframework.security.access.AccessDeniedException
class org.springframework.security.authentication.AuthenticationManager
class org.springframework.security.authentication.UsernamePasswordAuthenticationToken
class org.springframework.security.config.Customizer
class org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration
class org.springframework.security.config.annotation.web.builders.HttpSecurity
class org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer
class org.springframework.security.config.http.SessionCreationPolicy
class org.springframework.security.core.Authentication
class org.springframework.security.core.GrantedAuthority
class org.springframework.security.core.authority.SimpleGrantedAuthority
class org.springframework.security.core.context.SecurityContextHolder
class org.springframework.security.core.userdetails.UsernameNotFoundException
class org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder
class org.springframework.security.crypto.password.PasswordEncoder
class org.springframework.security.web.SecurityFilterChain
class org.springframework.security.web.authentication.HttpStatusEntryPoint
class org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter
class org.springframework.security.web.authentication.WebAuthenticationDetailsSource
class org.springframework.validation.FieldError
class org.springframework.web.bind.MethodArgumentNotValidException
class org.springframework.web.filter.OncePerRequestFilter
class org.springframework.web.servlet.config.annotation.CorsRegistry
class org.springframework.web.servlet.config.annotation.WebMvcConfigurer
interface com.transportation.metrobas.chat.MessageRepository
interface com.transportation.metrobas.gtfs.AgencyRepository
interface com.transportation.metrobas.gtfs.RouteRepository
interface com.transportation.metrobas.gtfs.StopRepository
interface com.transportation.metrobas.gtfs.StopTimesRepository
interface com.transportation.metrobas.gtfs.TransferStopsRepository
interface com.transportation.metrobas.gtfs.TransfersRepository
interface com.transportation.metrobas.gtfs.TripPointsRepository
interface com.transportation.metrobas.gtfs.TripRepository
interface com.transportation.metrobas.report.ReportRepository
interface com.transportation.metrobas.savedplaces.SavedPlaceRepository
interface com.transportation.metrobas.user.UserRepository
interface org.springframework.data.jpa.repository.JpaRepository
interface org.springframework.security.core.userdetails.UserDetails
interface org.springframework.security.core.userdetails.UserDetailsService
interface org.springframework.security.web.access.AccessDeniedHandler
interface org.springframework.security.web.authentication.logout.LogoutHandler
com.transportation.metrobas.auth.CustomAccessDeniedHandler --|> org.springframework.security.web.access.AccessDeniedHandler
com.transportation.metrobas.auth.CustomLogoutHandler --|> org.springframework.security.web.authentication.logout.LogoutHandler
com.transportation.metrobas.user.User --|> org.springframework.security.core.userdetails.UserDetails
com.transportation.metrobas.user.UserService --|> org.springframework.security.core.userdetails.UserDetailsService
@enduml