INSERT INTO transfers (transfer_id, min_transfer_time) VALUES ('1', '120');
INSERT INTO transfers (transfer_id, min_transfer_time) VALUES ('2', '120');
INSERT INTO transfers (transfer_id, min_transfer_time) VALUES ('3', '120');
INSERT INTO transfers (transfer_id, min_transfer_time) VALUES ('4', '120');
INSERT INTO transfers (transfer_id, min_transfer_time) VALUES ('5', '120');
INSERT INTO transfers (transfer_id, min_transfer_time) VALUES ('6', '120');
INSERT INTO transfers (transfer_id, min_transfer_time) VALUES ('7', '120');
INSERT INTO transfers (transfer_id, min_transfer_time) VALUES ('8', '120');
INSERT INTO transfers (transfer_id, min_transfer_time) VALUES ('9', '120');
INSERT INTO transfers (transfer_id, min_transfer_time) VALUES ('10', '120');

INSERT INTO transfers_stops (transfers_stop_id, transfer_id, stop_id, sequence) VALUES ('1', '1', 'survived.badge.line1', '1');
INSERT INTO transfers_stops (transfers_stop_id, transfer_id, stop_id, sequence) VALUES ('2', '1', 'scooped.duet.line2', '2');
INSERT INTO transfers_stops (transfers_stop_id, transfer_id, stop_id, sequence) VALUES ('3', '2', 'scooped.duet.line2', '1');
INSERT INTO transfers_stops (transfers_stop_id, transfer_id, stop_id, sequence) VALUES ('4', '2', 'survived.badge.line1', '2');
INSERT INTO transfers_stops (transfers_stop_id, transfer_id, stop_id, sequence) VALUES ('5', '3', 'homeward.nappy.line3', '1');
INSERT INTO transfers_stops (transfers_stop_id, transfer_id, stop_id, sequence) VALUES ('6', '3', 'wink.driftwood.line2', '2');
INSERT INTO transfers_stops (transfers_stop_id, transfer_id, stop_id, sequence) VALUES ('7', '4', 'wink.driftwood.line2', '1');
INSERT INTO transfers_stops (transfers_stop_id, transfer_id, stop_id, sequence) VALUES ('8', '4', 'homeward.nappy.line3', '2');
INSERT INTO transfers_stops (transfers_stop_id, transfer_id, stop_id, sequence) VALUES ('9', '5', 'trusts.imperious.line1', '1');
INSERT INTO transfers_stops (transfers_stop_id, transfer_id, stop_id, sequence) VALUES ('10', '5', 'trendy.misfits.line2', '2');
INSERT INTO transfers_stops (transfers_stop_id, transfer_id, stop_id, sequence) VALUES ('11', '6', 'trendy.misfits.line2', '1');
INSERT INTO transfers_stops (transfers_stop_id, transfer_id, stop_id, sequence) VALUES ('12', '6', 'trusts.imperious.line1', '2');
INSERT INTO transfers_stops (transfers_stop_id, transfer_id, stop_id, sequence) VALUES ('13', '7', 'nasser.gamal.line3', '1');
INSERT INTO transfers_stops (transfers_stop_id, transfer_id, stop_id, sequence) VALUES ('14', '7', 'nasser.gamal.line1', '2');
INSERT INTO transfers_stops (transfers_stop_id, transfer_id, stop_id, sequence) VALUES ('15', '8', 'nasser.gamal.line1', '1');
INSERT INTO transfers_stops (transfers_stop_id, transfer_id, stop_id, sequence) VALUES ('16', '8', 'nasser.gamal.line3', '2');
INSERT INTO transfers_stops (transfers_stop_id, transfer_id, stop_id, sequence) VALUES ('17', '9', 'kitkat.chocklet.zoom', '1');
INSERT INTO transfers_stops (transfers_stop_id, transfer_id, stop_id, sequence) VALUES ('18', '9', 'kitkat.chocklet.zoom2', '2');
INSERT INTO transfers_stops (transfers_stop_id, transfer_id, stop_id, sequence) VALUES ('19', '10', 'kitkat.chocklet.zoom2', '1');
INSERT INTO transfers_stops (transfers_stop_id, transfer_id, stop_id, sequence) VALUES ('20', '10', 'kitkat.chocklet.zoom', '2');