name: thirddraft
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  easy_splash_screen: ^1.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_map: ^6.1.0
  flutter_osm_plugin: ^0.70.4
  flutter_styled_toast: ^2.2.1
  get: ^4.6.6
  google_maps_flutter: ^2.6.0
  google_nav_bar: ^5.0.6
  http: ^1.2.1
  image_picker: ^1.1.2
  latlong2: ^0.9.0
  shared_preferences: ^2.2.2
  snapping_bottom_sheet: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
   - images/MetroBas.png
   - images/CTA.png
   - images/Metro.png
   - images/MicroBus.png
   - images/MiniBus.png